services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    # restart: unless-stopped
    volumes:
      - ./src:/app
      - ./Dataset:/Dataset
      - ./Dataset_test_code:/Dataset_test_code
      - ./models:/models
      - ./mlruns:/mlruns
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
      - RUNNING_IN_DOCKER=true
    mem_limit: 20g
    depends_on:
      - mlflow
    
  mlflow:
    image: ghcr.io/mlflow/mlflow
    ports:
      - 5001:5001
    volumes:
      - ./mlruns:/mlruns
    environment:
      MLFLOW_BACKEND_STORE_URI: /mlruns
      MLFLOW_SERVER_DEFAULT_ARTIFACT_ROOT: /mlruns
    command: mlflow server --host 0.0.0.0 --port 5001
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:5001/"]
      interval: 30s
      timeout: 10s
      retries: 5
